services:
  speed-cube-time:
    depends_on:
      - roach
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: speed-cube-time-rest-server
    hostname: speed-cube-time-rest-server
    networks:
      localnet:
        aliases:
          - db
    ports:
      - 80:8080
    environment:
      - APP_DSN=cockroach://username:roach@db:26257/speed_cube_time?sslmode=disable
      - APP_ENV=local
      - PGHOST=db
      - PGPORT=26257
      - PGUSER=username
      - PGPASSWORD=roach
      - PGDATABASE=speed_cube_time

    deploy:
      restart_policy:
        condition: on-failure
  roach:
    image: cockroachdb/cockroach:latest-v23.2
    container_name: roach
    hostname: db
    networks:
      - localnet
    expose:
      - 8080
      - 26257
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

  migrate:
    image: migrate/migrate
    container_name: migrate
    networks:
      - localnet
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "cockroach://username:roach@db:26257/speed_cube_time?sslmode=disable",
        "up",
      ]
    links:
      - roach
    depends_on:
      - roach
volumes:
  roach:

networks:
  localnet:
    driver: bridge
