FROM golang:alpine AS base
RUN apk update && \
    apk add --no-cache \
    curl \
    git \
    bash \
    make \
    ca-certificates 

FROM base as dev 

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /opt/app/api
CMD ["air"]


